seperate code build and code deploy so there is no lambda build conflict

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -94,12 +94,9 @@ commands:
           dir: sqs_lambda
 
 jobs:
-  build_and_deploy:
-    description: Builds and Optionaly deploys all the associated lambdas
+  run_code_build:
+    description: run codebuild to apply infrastructure
     parameters:
-      dir:
-        type: string
-        description: The lambda source directory
       env_lower_name:
         type: string
         description: The lower case env name
@@ -123,6 +120,69 @@ jobs:
           username: $DOCKERHUB_USERNAME
           password: $DOCKERHUB_PASSWORD
     steps:
+      - aws-cli/setup:
+          aws-access-key-id: << parameters.env_capital_name >>_AWS_ACCESS_KEY
+          aws-secret-access-key: << parameters.env_capital_name >>_AWS_SECRET_ACCESS_KEY
+          aws-region: << parameters.env_capital_name >>_AWS_DEFAULT_REGION
+      - run:
+          name: Setup CodeBuild environment variables
+          command: |
+            { \
+            echo 'export CODEBUILD_PROJECT_NAME="<< parameters.codebuild_project_name >>"'; \
+            echo 'export CODEBUILD_PROJECT_BRANCH="<< parameters.codebuild_project_branch >>"'; \
+            } >> "$BASH_ENV"
+      - run:
+          name: Run CodeBuild
+          command: |
+            echo -e "Starting CodeBuild for ${CODEBUILD_PROJECT_NAME}.\n"
+            BUILD_ID=$(aws codebuild start-build --project-name "$CODEBUILD_PROJECT_NAME" --environment-variables-override name=GIT_BRANCH,value="$CODEBUILD_PROJECT_BRANCH" --source-version "$CODEBUILD_PROJECT_BRANCH" --query 'build.id' --output text)
+            BUILD_STATUS="IN_PROGRESS"
+            # Wait for the CodeBuild to complete.
+            while [ "$BUILD_STATUS" == "IN_PROGRESS" ]; do
+              sleep 10
+              echo "Checking build status"
+              BUILD_STATUS=$(aws codebuild batch-get-builds --ids "$BUILD_ID" --query 'builds[0].buildStatus' --output text)
+              if [ "$BUILD_STATUS" == "IN_PROGRESS" ]; then
+                echo -e "Build is ${BUILD_STATUS}, waiting for build to complete...waiting for 10 seconds before next check...\n"
+              fi
+            done
+            if [ "$BUILD_STATUS" != "SUCCEEDED" ]; then
+              echo "CodeBuild failed to succeed with status ${BUILD_STATUS}"
+              exit 1
+            else
+              echo -e "CodeBuild succeeded\n"
+            fi
+      - store_artifacts:
+          path: /tmp/build.zip
+          
+  build_and_deploy_lambda:
+    description: build and deploy the app code to the lambda
+    parameters:
+      dir:
+        type: string
+        description: The lambda source directory
+      env_lower_name:
+        type: string
+        description: The lower case env name
+      env_capital_name:
+        description: The env capital name
+        type: string
+      lambda_lower_name:
+        type: string
+        description: The lower case lambda name
+      lambda_name:
+        description: The lambda capital name
+        type: string
+      deploy:
+        description: deploys on true
+        type: boolean
+        default: false
+    docker:
+      - image: circleci/node:14
+        auth:
+          username: $DOCKERHUB_USERNAME
+          password: $DOCKERHUB_PASSWORD
+    steps:
       - checkout
       - install_dependencies
       - run:
@@ -135,53 +195,24 @@ jobs:
             zip -r9 "/tmp/$CIRCLE_SHA1.zip" *
             mkdir -p /tmp
             cp "/tmp/$CIRCLE_SHA1.zip" /tmp/build.zip
+      - aws-cli/setup:
+          aws-access-key-id: << parameters.env_capital_name >>_AWS_ACCESS_KEY
+          aws-secret-access-key: << parameters.env_capital_name >>_AWS_SECRET_ACCESS_KEY
+          aws-region: << parameters.env_capital_name >>_AWS_DEFAULT_REGION
       - when:
           condition: << parameters.deploy >>
           steps:
-            - aws-cli/setup:
-                aws-access-key-id: << parameters.env_capital_name >>_AWS_ACCESS_KEY
-                aws-secret-access-key: << parameters.env_capital_name >>_AWS_SECRET_ACCESS_KEY
-                aws-region: << parameters.env_capital_name >>_AWS_DEFAULT_REGION
-            - run:
-                name: Setup CodeBuild environment variables
-                command: |
-                  { \
-                  echo 'export CODEBUILD_PROJECT_NAME="<< parameters.codebuild_project_name >>"'; \
-                  echo 'export CODEBUILD_PROJECT_BRANCH="<< parameters.codebuild_project_branch >>"'; \
-                  } >> "$BASH_ENV"
-            - run:
-                name: Run CodeBuild
-                command: |
-                  echo -e "Starting CodeBuild for ${CODEBUILD_PROJECT_NAME}.\n"
-                  BUILD_ID=$(aws codebuild start-build --project-name "$CODEBUILD_PROJECT_NAME" --environment-variables-override name=GIT_BRANCH,value="$CODEBUILD_PROJECT_BRANCH" --source-version "$CODEBUILD_PROJECT_BRANCH" --query 'build.id' --output text)
-                  BUILD_STATUS="IN_PROGRESS"
-                  # Wait for the CodeBuild to complete.
-                  while [ "$BUILD_STATUS" == "IN_PROGRESS" ]; do
-                    sleep 10
-                    echo "Checking build status"
-                    BUILD_STATUS=$(aws codebuild batch-get-builds --ids "$BUILD_ID" --query 'builds[0].buildStatus' --output text)
-                    if [ "$BUILD_STATUS" == "IN_PROGRESS" ]; then
-                      echo -e "Build is ${BUILD_STATUS}, waiting for build to complete...waiting for 10 seconds before next check...\n"
-                    fi
-                  done
-                  if [ "$BUILD_STATUS" != "SUCCEEDED" ]; then
-                    echo "CodeBuild failed to succeed with status ${BUILD_STATUS}"
-                    exit 1
-                  else
-                    echo -e "CodeBuild succeeded\n"
-                  fi
             - run:
                 name: Upload Package
-                command: aws s3 cp "/tmp/$CIRCLE_SHA1.zip" s3://pocket-fxawebhookproxy-<< parameters.env_lower_name >>-sqs-fxa-events/
+                command: aws s3 cp "/tmp/$CIRCLE_SHA1.zip" s3://pocket-fxawebhookproxy-<< parameters.env_lower_name >>-<< parameters.lambda_lower_name >>/
             - pocket/deploy_lambda:
-                s3-bucket: pocket-fxawebhookproxy-<< parameters.env_lower_name >>-sqs-fxa-events
+                s3-bucket: pocket-fxawebhookproxy-<< parameters.env_lower_name >>-<< parameters.lambda_lower_name >>
                 aws-access-key-id: << parameters.env_capital_name >>_AWS_ACCESS_KEY
                 aws-secret-access-key: << parameters.env_capital_name >>_AWS_SECRET_ACCESS_KEY
                 aws-region: << parameters.env_capital_name >>_AWS_DEFAULT_REGION
-                codedeploy-application-name: FxAWebhookProxy-<< parameters.env_capital_name >>-Sqs-FxA-Events-Lambda
-                codedeploy-deployment-group-name: FxAWebhookProxy-<< parameters.env_capital_name >>-Sqs-FxA-Events-Lambda
-                function-name: FxAWebhookProxy-<< parameters.env_capital_name >>-Sqs-FxA-Events-Function
-
+                codedeploy-application-name: FxAWebhookProxy-<< parameters.env_capital_name >>-<< parameters.lambda_name >>-Lambda
+                codedeploy-deployment-group-name: FxAWebhookProxy-<< parameters.env_capital_name >>-<< parameters.lambda_name >>-Lambda
+                function-name: FxAWebhookProxy-<< parameters.env_capital_name >>-<< parameters.lambda_name >>-Function
       - store_artifacts:
           path: /tmp/build.zip
 
@@ -245,73 +276,104 @@ workflows:
           context: pocket
           name: test_functional
 
+      - run_code_build:
+          <<: *only_dev
+          context: pocket
+          name: run_dev_code_build
+          codebuild_project_name: FxAWebhookProxy-Dev
+          codebuild_project_branch: dev
+          env_lower_name: dev
+          env_capital_name: Dev
+
+      - run_code_build:
+          <<: *only_main
+          context: pocket
+          name: run_prod_code_build
+          codebuild_project_name: FxAWebhookProxy-Prod
+          codebuild_project_branch: main
+          env_lower_name: prod
+          env_capital_name: Prod
+
       # SQS lambda deployment
       # Build the sqs lambda on each branch
-      - build_and_deploy:
+      - build_and_deploy_lambda:
           <<: *not_dev_main
           context: pocket
           name: build_sqs_lambda
           dir: sqs_lambda
           env_lower_name: prod
           env_capital_name: Prod
+          lambda_lower_name: sqs-fxa-events
+          lambda_name: Sqs-FxA-Events
+
 
       # Build & Deploy SQS lambda on dev branch
-      - build_and_deploy:
+      - build_and_deploy_lambda:
           <<: *only_dev
           context: pocket
           name: deploy_sqs_lambda_dev
           dir: sqs_lambda
-          codebuild_project_name: FxAWebhookProxy-Dev
-          codebuild_project_branch: dev
           env_lower_name: dev
           env_capital_name: Dev
+          lambda_lower_name: sqs-fxa-events
+          lambda_name: Sqs-FxA-Events
           deploy: true
+          requires:
+            - run_dev_code_build
 
       # Build & Deploy Sqs lambda in main branch
-      - build_and_deploy:
+      - build_and_deploy_lambda:
           <<: *only_main
           context: pocket
           name: deploy_sqs_lambda_prod
           dir: sqs_lambda
-          codebuild_project_name: FxAWebhookProxy-Prod
-          codebuild_project_branch: main
           env_lower_name: prod
           env_capital_name: Prod
+          lambda_lower_name: sqs-fxa-events
+          lambda_name: Sqs-FxA-Events
           deploy: true
+          requires:
+            - run_prod_code_build
 
       # Api Gateway lambda deployment
       # Build the api gateway lambda on each branch
-      - build_and_deploy:
+      - build_and_deploy_lambda:
           <<: *not_dev_main
           context: pocket
           name: build_api_gateway_lambda
           dir: gateway_lambda
           env_lower_name: prod
           env_capital_name: Prod
+          lambda_lower_name: apigateway-fxa-events
+          lambda_name: ApiGateway-FxA-Events
 
       # Build & Deploy Api gateway lambda on dev branch
-      - build_and_deploy:
+      - build_and_deploy_lambda:
           <<: *only_dev
           context: pocket
           name: deploy_api_gateway_lambda_dev
           dir: gateway_lambda
-          codebuild_project_name: FxAWebhookProxy-Dev
-          codebuild_project_branch: dev
           env_lower_name: dev
           env_capital_name: Dev
+          lambda_lower_name: apigateway-fxa-events
+          lambda_name: ApiGateway-FxA-Events
           deploy: true
+          requires:
+            - run_dev_code_build
 
       # Build & Deploy Api gateway lambda in main branch
-      - build_and_deploy:
+      - build_and_deploy_lambda:
           <<: *only_main
           context: pocket
           name: deploy_api_gateway_lambda_prod
           dir: gateway_lambda
-          codebuild_project_name: FxAWebhookProxy-Prod
-          codebuild_project_branch: main
           env_lower_name: prod
           env_capital_name: Prod
+          lambda_lower_name: apigateway-fxa-events
+          lambda_name: ApiGateway-FxA-Events
           deploy: true
+          requires:
+            - run_prod_code_build
 
       # Prod
       - pocket/setup_deploy_params:
